import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "@/shared/config/queryClient";

const inter = Inter({
   display: "swap",
   subsets: ["latin"],
});

export const metadata: Metadata = {
   title: "XDevelop Test",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body className={inter.className}>
            <Providers>{children}</Providers>
         </body>
      </html>
   );
}
